version: "3"

services:
  nginxproxy:
    depends_on:
      - nginx
      - baeumdb
    image: nginx:alpine
    container_name: proxyserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot-etc:/etc/letsencrypt
      - ./myweb:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: mywebserver
    restart: always
    volumes:
      - ./myweb:/usr/share/nginx/html

  baeumdb:
    image: postgres
    env_file:
      - ./.env
    container_name: postgres
    restart: always
    volumes:
      - mydb:/var/lib/postgresql

  app:
    build:
      context: ./
      dockerfile: Dockerfile-baeum
    env_file:
      - ./.env
    depends_on:
      - baeumdb
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh baeumdb:5432 -t 10
        npm run start
    container_name: nestjs-api
    restart: always

  certbot:
    depends_on:
      - nginxproxy
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./myweb:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email gyals0386@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d makevalue.net -d www.makevalue.net

volumes:
  mydb: